-- MySQL Script generated by MySQL Workbench
-- Fri Jul 28 11:00:01 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mediadb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mediadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mediadb` DEFAULT CHARACTER SET utf8 ;
USE `mediadb` ;

-- -----------------------------------------------------
-- Table `mediadb`.`Artist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mediadb`.`Artist` ;

CREATE TABLE IF NOT EXISTS `mediadb`.`Artist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `nickname` VARCHAR(45) NOT NULL,
  `birthdate` DATE NULL,
  `birthplace` VARCHAR(45) NULL,
  `biography` TEXT NULL,
  `picture` VARCHAR(255) NULL,
  `website` VARCHAR(2083) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mediadb`.`Album`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mediadb`.`Album` ;

CREATE TABLE IF NOT EXISTS `mediadb`.`Album` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `releasedate` VARCHAR(45) NULL,
  `numbersong` INT NULL,
  `Artist_id` INT NOT NULL,
  `stock` INT NULL,
  `price` DOUBLE NULL,
  `cover` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Album_Artist1_idx` (`Artist_id` ASC),
  CONSTRAINT `fk_Album_Artist1`
    FOREIGN KEY (`Artist_id`)
    REFERENCES `mediadb`.`Artist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mediadb`.`Award`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mediadb`.`Award` ;

CREATE TABLE IF NOT EXISTS `mediadb`.`Award` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mediadb`.`Artist_has_Award`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mediadb`.`Artist_has_Award` ;

CREATE TABLE IF NOT EXISTS `mediadb`.`Artist_has_Award` (
  `Artist_id` INT NOT NULL,
  `Award_id` INT NOT NULL,
  `dateDelivery` VARCHAR(45) NULL,
  `place` VARCHAR(45) NULL,
  PRIMARY KEY (`Artist_id`, `Award_id`),
  INDEX `fk_Artist_has_Award_Award1_idx` (`Award_id` ASC),
  INDEX `fk_Artist_has_Award_Artist1_idx` (`Artist_id` ASC),
  CONSTRAINT `fk_Artist_has_Award_Artist1`
    FOREIGN KEY (`Artist_id`)
    REFERENCES `mediadb`.`Artist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Artist_has_Award_Award1`
    FOREIGN KEY (`Award_id`)
    REFERENCES `mediadb`.`Award` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mediadb`.`Song`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mediadb`.`Song` ;

CREATE TABLE IF NOT EXISTS `mediadb`.`Song` (
  `idsong` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `duration` INT NULL,
  `Album_id` INT NOT NULL,
  PRIMARY KEY (`idsong`),
  INDEX `fk_Song_Album1_idx` (`Album_id` ASC),
  CONSTRAINT `fk_Song_Album1`
    FOREIGN KEY (`Album_id`)
    REFERENCES `mediadb`.`Album` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mediadb`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mediadb`.`Category` ;

CREATE TABLE IF NOT EXISTS `mediadb`.`Category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mediadb`.`Album_has_Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mediadb`.`Album_has_Category` ;

CREATE TABLE IF NOT EXISTS `mediadb`.`Album_has_Category` (
  `Album_id` INT NOT NULL,
  `Category_id` INT NOT NULL,
  PRIMARY KEY (`Album_id`, `Category_id`),
  INDEX `fk_Album_has_Category_Category1_idx` (`Category_id` ASC),
  INDEX `fk_Album_has_Category_Album1_idx` (`Album_id` ASC),
  CONSTRAINT `fk_Album_has_Category_Album1`
    FOREIGN KEY (`Album_id`)
    REFERENCES `mediadb`.`Album` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Album_has_Category_Category1`
    FOREIGN KEY (`Category_id`)
    REFERENCES `mediadb`.`Category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mediadb`.`Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mediadb`.`Role` ;

CREATE TABLE IF NOT EXISTS `mediadb`.`Role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `roleName` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mediadb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mediadb`.`User` ;

CREATE TABLE IF NOT EXISTS `mediadb`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NULL,
  `Role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_User_Role1_idx` (`Role_id` ASC),
  CONSTRAINT `fk_User_Role1`
    FOREIGN KEY (`Role_id`)
    REFERENCES `mediadb`.`Role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mediadb`.`Bag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mediadb`.`Bag` ;

CREATE TABLE IF NOT EXISTS `mediadb`.`Bag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lastAccessDate` DATETIME NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Bag_User1_idx` (`User_id` ASC),
  CONSTRAINT `fk_Bag_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `mediadb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mediadb`.`Picture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mediadb`.`Picture` ;

CREATE TABLE IF NOT EXISTS `mediadb`.`Picture` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uri` VARCHAR(255) NULL,
  `takeOn` DATETIME NULL,
  `Artist_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Picture_Artist1_idx` (`Artist_id` ASC),
  CONSTRAINT `fk_Picture_Artist1`
    FOREIGN KEY (`Artist_id`)
    REFERENCES `mediadb`.`Artist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mediadb`.`Bag_Line`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mediadb`.`Bag_Line` ;

CREATE TABLE IF NOT EXISTS `mediadb`.`Bag_Line` (
  `Album_id` INT NOT NULL,
  `Bag_id` INT NOT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`Album_id`, `Bag_id`),
  INDEX `fk_Album_has_Bag_Bag1_idx` (`Bag_id` ASC),
  INDEX `fk_Album_has_Bag_Album1_idx` (`Album_id` ASC),
  CONSTRAINT `fk_Album_has_Bag_Album1`
    FOREIGN KEY (`Album_id`)
    REFERENCES `mediadb`.`Album` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Album_has_Bag_Bag1`
    FOREIGN KEY (`Bag_id`)
    REFERENCES `mediadb`.`Bag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
